# .readthedocs.yaml configuration file
# Read the Docs configuration for FastGenAPI

version: 2

# Build tools required for the project
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Python dependencies required to build the docs
python:
  install:
    - requirements: docs/requirements.txt

# Sphinx project configuration
sphinx:
  configuration: docs/conf.py

# Specify the format of the documentation output
formats: all

# Build documentation from Markdown files
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

